### ISSUE TITLE
Google+ usage example has a typo

### ISSUE THREAD

**Issue by neamtua** [SocialiteProviders/socialiteproviders.github.io#8]
In the docs for Google+ usage you have

`return Socialite::with('google+')->redirect();`

It should be

`return Socialite::with('google')->redirect();`

or an error saying "Driver [google+] not supported" will be thrown.

**Comment by AndyWendt** [comment]
Thanks for this

**Comment by AndyWendt** [comment]
@DraperStudio I tried a couple of quick fixes--they didn't fix the issue.  I am at work right now so I cannot go in depth.

**Comment by DraperStudio** [comment]
The issue is the name of the provider since we use it as Placeholders. Maybe we rename the provider to Google in the docs just for the sake of it being shown the right way.

Will take a closer look later.

**Comment by neamtua** [comment]
Would have made a PR but I didn't have enough time to figure out how your whole cms system works :)

**Comment by DraperStudio** [comment]
It is quite simple. We reuse the page title all over the page, in this case and position we just transform the title to lowercase and because the Page title is Google+ you use google+ in this specific spot.

I either will add an extra field so we can use different values for this spot or rename the provider from GooglePlus to Google to show it correctly. Hope I get a free minute later to fix that.

**Comment by DraperStudio** [comment]
Should be displayed correctly now.
